elastic-query-service:
  version: v1
  custom-audience: elastic-query-service

server:
  port: 9193
  servlet:
    context-path: /elastic-query-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/microservices-realm
          jwk-set-uri: http://localhost:9090/auth/realms/microservices-realm/protocol/openid-connect/certs

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  user-name: pasindu
  password: pasindu
  roles: USER